version: '2'

services:

  dms:
    image: andrglo/everest:12.16.1
    hostname: pg-cr-layer
    command: tail -f /dev/null
    working_dir: /root/pg-cr-layer
    volumes:
      # - ./docker_fish_history:/root/.config/fish/fish_history
      - .:/root/pg-cr-layer
    environment:
      - NODE_ENV=test
      - POSTGRES_HOST=postgres
    restart: always

  postgres:
    image: postgres:12.2-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always


